### PR TITLE
Detect accidental duplication in production bundles

### PR DESCRIPTION
**Pull request by nvie**
This adds a code snippet to detect cases where complex bundle setups or certain monorepo setups lead to duplicated inclusion of both the CJS and ESM versions of our library in the final production bundle. The problem with that is that object instances generated with one "runtime copy" of the library end up being sent to APIs from the other "runtime copy", which leads to various bugs.

This is a proposed fix for #432.

Not sure if I actually like this solution. Would love to get everyone's opinion on this? Good idea? Terrible idea? A different approach?

### CODE REVIEW

**Comment by ofoucherot** [comment]
I don't see any downside to this solution but I don't know if it's the best approach. 

I will do more research tomorrow but could we use the Approach #1 from the Nodejs [doc](https://nodejs.org/api/packages.html#dual-commonjses-module-packages ) on "Writing dual packages while avoiding or minimizing hazards" ?

**Comment by nvie** [comment]
> …could we use the Approach #1 from the Nodejs [doc](https://nodejs.org/api/packages.html#dual-commonjses-module-packages)…

Ah! _There_ it was! I've been trying to find back a blog post of some kind that I read about that trick in the past, but couldn't recollect it. This Node doc page was exactly what I was trying to recall — thanks for surfacing it for me.

I remember studying this once when I wanted to do the same thing for publishing decoders, but found it to be too cumbersome to set up. I think I didn't want to bother writing a custom code generator for those wrappers, and also didn't feel like maintaining the mapping manually. Back then I didn't find a tool that would enable this wrapping automatically for all exported symbols.

Will take a look to see if it's any easier today.

**Comment by nvie** [comment]
Was thinking of adding the following section to the [Troubleshooting](https://liveblocks.io/docs/guides/troubleshooting) section in the docs to link to in the warning message:

> ### Avoiding bundling Liveblocks twice in your production bundle
> 
> We publish Liveblocks packages to NPM in both CJS and ESM formats. When your bundler supports modern code, it will automatically use the ESM sources. This has several benefits, like tree-shaking.
> 
> However, in certain complex bundler setups, we've seen cases where Liveblocks code  accidentally gets included twice—both the CJS and ESM implementations end up in production bundles. If this happens, it self-detects this case and issues the following warning in the console at runtime:
> 
> ```
> @liveblocks/client appears twice in your bundle (as CJS and ESM).
> ```
> 
> This scenario should obviously be avoided. On the one hand, it means your production bundle size is unnecessarily bloated. But worse, it leads to hard-to-debug bugs caused by two separately running Liveblocks client states. When you hit this situation, it's well possible that the Liveblocks package isn't the only package that is getting included twice, so please do double-check your bundlers configuration and dependency tree.

Not sure if we can be more helpful/concrete in the _actual_ way to debug this issue, since so much of the nitty gritty details here depend on the actual bundler and their configuration that there are myriad ways to end up in this scenario…?

Ideas?

**Comment by ofoucherot** [comment]
> ```
> 
> ```

Let's forget the wrapping solution then. It looks like there is no "standard" solution. The warning that contains a link to the documentation is enough I think.

**Comment by nvie** [comment]
I dug a little deeper here, and I think the problem might be bigger than we originally anticipated. This isn't an issue just for complex bundler setups or monorepos. Even our relatively standard Next.js e2e test app setup (basically a standard `npx create-next-app` unless I'm overlooking something here) seems to be affected and is bundling our app twice… 🤔

After some deeper debugging, this seems to happen in the bundle:

```
==> First import of @liveblocks/client CJS in .next/server/pages/storage/list.js:17:75)
==> Dupe import of @liveblocks/client ESM in .next/server/pages/storage/list.js:21:77)
```

So first the CJS version is required from L17, then the ESM version is imported from L21. That seems bad!

That generated Webpack code looks like:

Screen Shot 2022-08-22 at 11 51 37@2x

Here, L17's CJS-style import corresponds to the original source's line: https://github.com/liveblocks/liveblocks/blob/main/e2e/next-sandbox/pages/storage/list.tsx#L1

Next L21's import corresponds to https://github.com/liveblocks/liveblocks/blob/main/e2e/next-sandbox/pages/storage/list.tsx#L4 which in turn does https://github.com/liveblocks/liveblocks/blob/main/e2e/next-sandbox/utils/createClient.ts#L1

It's unclear to me why the first one uses the CJS module, while the second is using an ESM module. The dual package hazard problem seems real.

@ofoucherot @GuillaumeSalles Perhaps it would be better to follow the ESM wrapping technique after all, and sacrifice tree-shakability in return?

**Comment by nvie** [comment]
Closing this in favor of #441.

**Pull request closed without merging**
