### PR TITLE
Update brand, assets, and docs

### PR DESCRIPTION
**Pull request by pierrelevaillant**
This refreshes Liveblocks README assets (_header, wordmark, examples thumbnails..._).

### CODE REVIEW

**Review by stevenfabre — COMMENTED** [review]
Looks great overall!

Small feedback:
- Why have you moved the logo up in `header-wordmark-dark` and `header-wordmark-light`? It looks slightly off-center vertically, but I think we shouldn't even align it in the center vertically. The reason why it's close to the bottom is so that it feels close to the badges. I'd suggest keeping that.

**Review by marcbouchenoire — CHANGES_REQUESTED** [review]
I'd suggest renaming the branch and PR (to `Update brand` maybe?) since it includes docs fixes too, but it's good to have only one PR here!

I have the same feedback as Steven, all animated headers should keep the same alignment (you can even see the cursors passing above the content when it's in the center like that).

**Review by marcbouchenoire — CHANGES_REQUESTED** [review]
The logo in `header-light.svg` and `header-dark.svg` also needs to move down in the same way.

**Review by marcbouchenoire — APPROVED** [review]
👌

**Pull request merged**
